on: [push, pull_request]

name: CI for 'text-replace'

jobs:

  build:
    name: Test the package
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghc:
          - '8.2.2'
          - '8.4.3'
          - '8.6.1'
          - '8.8.1'
          - '8.10.2'
          - '9.0.1'

    steps:
      - uses: actions/checkout@v2

      - name: Cache Haskell dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.variant }}-${{ hashFiles('**/*.cabal', '.github/workflows/test.hs') }}
          restore-keys: |
              ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.variant }}-
              ${{ runner.os }}-${{ matrix.ghc }}-
              ${{ runner.os }}-

      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Test
        run: runhaskell --ghc-arg='-package process' ./.github/workflows/test.hs
        env:
          ghc: ${{ matrix.ghc }}
